export const PLUS = 'PLUS'
export const MINUS = 'MINUS'
export const MULTIPLY = 'MULTIPLY'
export const DIVIDE = 'DIVIDE'
export const DOT = 'DOT'
export const EVALUATE = 'EVALUATE'
export const CLEAR = 'CLEAR'
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION'

export const OPERATOR_CLICK = 'OPERATOR_CLICK'
export const DIGIT_CLICK = 'DIGIT_CLICK'
